name: Lint Markdown

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.md'
      - '.markdownlint-cli2.jsonc'

permissions:
  contents: read

jobs:
  lint:
    uses: borch-ai/.github/.github/workflows/markdown-lint.yml@6fd0a9a05fa00d21159402147a3445af04a191c5 # v1.0.0
