name: PR Description

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  contents: read
  pull-requests: read

jobs:
  check:
    uses: borch-ai/.github/.github/workflows/pr-description.yml@6fd0a9a05fa00d21159402147a3445af04a191c5 # v1.0.0
